package forge.ai.decision;

public enum AiDecisionFailureReason {
    DISABLED,
    INVALID_CONFIG,
    TIMEOUT,
    CONNECTION,
    HTTP_ERROR,
    EMPTY_RESPONSE,
    MALFORMED_RESPONSE,
    INVALID_OPTION,
    DECISION_ID_MISMATCH,
    FINGERPRINT_MISMATCH,
    PROVIDER_EXCEPTION,
    NO_SAFE_ACTION_SET,
    ACTION_ID_MISMATCH,
    STALE_ACTION_SET,
    REVALIDATION_FAILED
}
